//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34003
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public class Deck
		{		
		public int deckId { get; set; }
		public String deckName { get; set; }
		public int userId { get; set; }
		public Boolean isActive { get; set; }

				public Deck ()
				{
				}
		}
}

