//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34003
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public class WarriorCard:Card
		{
			private int cardArmor;
			private int cardDamage;
			private int cardHealth;

				public WarriorCard ()
				{
					
				}
		}
}

